### ISSUE TITLE
[Feature 8] Cloud Storage

### ISSUE THREAD

**Issue by ScottCTD** [CSC207-2022F-UofT/course-project-bill-gates#25]
# Initiations

- We would like to have a server to hold all of our Dev data and testing data, so then we would not be bothered to set up a database on everybody's computer. (also cloud server is more convenient for the final presentation)

# Design

- I will create a server and install the necessary software.
- Database: MySQL 8.0

# Implementation Details

- Microsoft Azure Database for MySQL flexible server

# Connection Detail
```
hostname=bill-gates-database.mysql.database.azure.com
username=scott
password=Billgates@
ssl-mode=require
```

Database Name: `bill`

**Comment by Lei-Tin** [comment]
We can work on the cloud servers later on, I looked up on some options that we have: 

Either 1. Setup your own MySQL server on your own machine (Not so smart, because you'd need to have your machine run 24 * 7 and open connection to all sources)

Or 2. Get some cloud servers like Google Cloud, Microsoft Azure, Amazon Cloud, stuff like that

What I'm seeing the most in cloud recommendation is Google cloud, so maybe we can look into that
