### ISSUE TITLE
[Improvement] Return values of methods in `DatabaseGateway` could be useful.

### ISSUE THREAD

**Issue by ScottCTD** [CSC207-2022F-UofT/course-project-bill-gates#59]
- `DatabaseGateway.getUserData(String)` could return `null` if the given user does not exist in the database.
- Now, the behavior of failing to find a user is throwing a `RuntimeException`, which is not very cool. 
- We can generalize this as all methods should return something that is useful.
- For example, the `getBillData` method may return `null` if the table related to the given id is not in the database, instead of throwing a `SQLException`.

**Comment by Lei-Tin** [comment]
I have a small problem. 

If we were to select users and entry, that is fine. We can return `null` if the username / entry_id in question cannot be found. As the query `ResultSet` will be empty. 

However, for other "Getter" methods from the database, if we pass in a table ID that is not quite right, MySQL gives a SQLException right away, and there is no way to tell whether this SQLException is actually caused by a wrong table ID or simply a bad connection. 

Similar result goes for `createBillTable` and methods that aren't specific to grab a single result. 


Also, aside from this, in my next PR, I will also include a SQL Script to generate a sample dataset that we can use to test things. Stay tuned for that!
